# Generated by Django 4.0.5 on 2022-06-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatusersonline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatUsersOnline',
        ),
    ]
