# Generated by Django 4.0.5 on 2022-06-22 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_onlinechatusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinechatusers',
            name='group_name',
            field=models.CharField(max_length=50, null=True, verbose_name='ИмяГруппы'),
        ),
        migrations.AlterField(
            model_name='onlinechatusers',
            name='online',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
