# Generated by Django 4.0.5 on 2022-06-22 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_delete_chatusersonline'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineChatUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Онлайн',
                'verbose_name_plural': 'Онлайн',
            },
        ),
    ]
