# Generated by Django 4.0.5 on 2022-06-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogAuth', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
