# Generated by Django 4.0.5 on 2022-06-20 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crblog', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviwes',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='crblog.blog', verbose_name='Блог'),
        ),
    ]
